name: selenium-webdriver-es-modules-babeljs-jasmine-assert
'on':
  push: null
  schedule:
    - cron: 30 3 1-31/2 * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
        env:
          CI: true
      - name: Lint
        run: npm run lint --if-present
      - name: Build
        run: npm run build --if-present
      - name: Executing tests
        run: npm run test
=======
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: INSTALL
      run: npm ci
      env:
        CI: true
    - name: LINT
      run: npm run lint
    - name: TEST
      run: npm run test
>>>>>>> 3941c5fcc35433c71378312a4eb0408e5037615d
